### PR TITLE
Logs saved over route changes

### PR DESCRIPTION
**Pull request by ljmerza**
If you go back to the home page, your logs get deleted when you try to go back to the time-entries route. I moved the 'sidebar' code to the App.vue component and had a $dispatch() event from logTime.vue propagate to the App.vue.

App.vue shares its array of timeEntries with the TimeEntries.vue component through 'props'. I also made the logTime.vue component redirect to TimeEntries.vue after saving a new log so the form would close out. Finally, the hard coded user wouldn't work in the new layout and I noticed a comment of it being temporary for a further project so I got rid of it. I tried to keep the comments the same but some didn't make sense anymore and I deleted them.  

It was also complaining about duplicate entries and would break if you added the same entry (it would overwrite the old one but not update the total time) so I added track by $index to the v-for loop and the $index is what's passed in the $dispatch event.

A lot of changes but I tested it and it will work better for future add ons to this project. This is my first time contributing to Github so if I'm doing something wrong let me know. Learned a lot by fixing this. Thanks for the article!

### CODE REVIEW

**Comment by ljmerza** [comment]
Oh and it was complaining about duplicate entries so I added track by $index to the v-for loop and the $index is what's passed in the $dispatch event.

**Comment by chenkie** [comment]
Thanks for your PR, some nice changes here :)

I think I'll hold off on merging until I get the server side in place, as there were a few things I wanted to look at changing on the front end at that time. Let's work together once that's done to get your changes in.

**Comment by Joshfindit** [comment]
Last commit was 6 months ago. Is it possible that the server side isn't as interesting any more?

**Comment by ljmerza** [comment]
Vue has switched to version 2 and gets rid of the dispatch event stuff completely.

**Pull request closed without merging**
